### ISSUE TITLE
About one-hop neighborhood context and two-hop monophily

### ISSUE THREAD

**Issue by ChanglongZheng** [tengxiao1/GraphACL#3]
方便起见，我还是用中文吧。
您的工作简洁高效，符合直觉，先👍一个。
论文6.2中有这样的一句：“we attribute our significant improvement to modeling the one-hop neighborhood context and two-hop monophily.” 有一个疑问是这样的：
"two-hop monophily"应该是"one-hop neighborhood context"的补充吧？大多数情况下"two-hop monophily"都会属于"one-hop neighborhood context"的，除了一些例外（比如一个结点只有一个邻居，就没有这种"one-hop neighborhood context"可言）

**Comment by tengxiao1** [comment]
Thank you for your interest. Some two-hop neighbors share similar semantic features but do not share similar one-hop neighborhood contexts in the real world, especially when we have multi-class (n>2) or the graph shows mixture patterns.

**Comment by ChanglongZheng** [comment]
I get it, you're right, we must consider situations like multi-class.
Thanks for your reply :)
